# Generated by Django 5.0.2 on 2026-04-22 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_remove_profile_about_post_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='joined_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
