# Generated by Django 5.0.2 on 2026-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_attendees'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Reported', 'Reported'), ('Scheduled', 'Clean-up Scheduled'), ('Cleared', 'Cleared'), ('Disabled', 'Disabled'), ('Join', 'Join')], default='Reported', max_length=100),
        ),
    ]
